Repository DLTcollab/tangle-accelerator, pull requests merged in 2019-05, with the labels that each got.

#164 fix(server): Evaluate whole status_t code in server.cc
  accelerator/server.cc
Labels: ready for review

#166 fix(driver): Fix wrong testing info
  tests/driver.c
Labels: bug, ready for review

#163 feat(reg): Add shell script for running runner.py
  tests/regression/0_pull_build.sh
  tests/regression/1_run_regression_test.sh
  tests/regression/requirements.txt
Labels: ready for review

#165 feat(server): Implement server core functions with microhttpd
  accelerator/BUILD
  accelerator/errors.h
  accelerator/http.c
  accelerator/http.h
  accelerator/main.c
Labels: Core, ready for review

#174 fix(reg): Fix CI execution errors
  tests/regression/0_build.sh
  tests/regression/1_close_TA.sh
  tests/regression/1_run_TA.sh
  tests/regression/1_run_regression_test.sh
  tests/regression/requirements.txt
  tests/regression/runner.py
Labels: bug

#176 feat(server): Implement signal handler to terminate TA
  accelerator/BUILD
  accelerator/main.c
Labels: Core, enhancement, ready for review

#181 fix(seria): Fix `const` placement and if statement
  serializer/serializer.c
  serializer/serializer.h
Labels: bug

#156 feat(api): Add send_transfer regression test
  accelerator/errors.h
  serializer/serializer.c
  tests/regression/1_close_TA.sh
  tests/regression/1_run_TA.sh
  tests/regression/runner.py
Labels: enhancement, ready for review

#185 feat(bazel): Import hiredis dependency through bazel
  WORKSPACE
  tests/BUILD
  third_party/BUILD
  third_party/BUILD.hiredis
  third_party/third_party.bzl
  utils/BUILD
  utils/backend_redis.c
Labels: enhancement

#157 feat(api): Impl api_send_trytes()
  accelerator/BUILD
  accelerator/apis.c
  accelerator/apis.h
  accelerator/common_core.c
  accelerator/errors.h
  serializer/serializer.c
  serializer/serializer.h
  tests/driver.c
  tests/test_common.cc
  tests/test_define.h
  tests/test_serializer.c
Labels: API, ready for review

#187 feat(server): Implement URL parser
  accelerator/errors.h
  accelerator/http.c
Labels: Core, enhancement

#191 feat(server): Implement generate_address API callback function
  accelerator/http.c
Labels: Core, enhancement
