Repository DLTcollab/tangle-accelerator, pull requests merged in 2019-07, with the labels that each got.

#233 feat(cache): Set the cache default as off
  accelerator/common_core.c
  accelerator/config.c
  accelerator/config.h
  accelerator/errors.h
  accelerator/message.h
  tests/test_cache.c
  tests/test_common.cc
  utils/backend_redis.c
  utils/cache.h
Labels: Enhancement, Ready for review

#231 feat(server): Implement req / res log message
  accelerator/http.c
Labels: Ready for review

#232 feat(api): Implement find_transaction_objects and find_transactions
  accelerator/apis.c
  accelerator/apis.h
  accelerator/common_core.c
  accelerator/common_core.h
  accelerator/server.cc
  request/request.h
  request/ta_find_transaction_objects.c
  request/ta_find_transaction_objects.h
  request/ta_send_mam.h
  request/ta_send_transfer.h
  response/response.h
  response/ta_find_transactions.h
  response/ta_find_transactions_obj.h
  response/ta_generate_address.h
  response/ta_get_tips.h
  response/ta_get_transaction_object.c
  response/ta_get_transaction_object.h
  response/ta_send_mam.h
  response/ta_send_transfer.h
  serializer/serializer.c
  serializer/serializer.h
  tests/driver.c
  tests/iota_api_mock.cc
  tests/iota_api_mock.hh
  tests/regression/1_run_TA_API.sh
  tests/regression/runner.py
  tests/test_common.cc
  tests/test_define.h
  tests/test_serializer.c
  utils/cache.h
  utils/pow.h
Labels: API, Enhancement, Ready for review

#238 fix: Detect cache server turning off situation
  accelerator/common_core.c
Labels: Bug

#237 fix(api): Update find txn related apis
  accelerator/http.c
Labels: API, Ready for review

#239 fix(server): Check request body in POST api callback functions
  accelerator/http.c
Labels: Bug, Core, Ready for review

#240 fix(server): Modify error code switch case in set_response_content
  accelerator/http.c
Labels: Bug, Core, Ready for review

#235 refactor(api): Fetch MAM messge with channel ID
  accelerator/apis.c
  accelerator/apis.h
  accelerator/common_core.c
  accelerator/common_core.h
  map/mode.c
  map/mode.h
  tests/driver.c
  tests/test_define.h
  tests/test_map_mode.c
Labels: API, Core, Ready for review

#252 feat(api): Refactor response JSON format
  serializer/serializer.c
  tests/test_serializer.c
Labels: API, Ready for review

#249 feat(server): Enable using thread for per request
  accelerator/http.c
Labels: Core, Enhancement, Ready for review

#256 feat: Synchronize to stable entangled version
  WORKSPACE
Labels: Enhancement

#255 feat(API): Add tag related fetching APIs back
  accelerator/apis.c
  accelerator/apis.h
  accelerator/common_core.c
  accelerator/common_core.h
  accelerator/server.cc
  serializer/BUILD
  serializer/serializer.c
  serializer/serializer.h
  tests/driver.c
Labels: API, Ready for review
