Repository DLTcollab/tangle-accelerator, pull requests merged in 2019-06, with the labels that each got.

#200 feat(server): Implement get_tips_pair API callback function
  accelerator/http.c
Labels: Core, enhancement

#203 fix: Fix unicode, memory leak and lost transaciton errors
  accelerator/apis.c
  accelerator/errors.h
  serializer/serializer.c
  tests/regression/runner.py
  tests/test_define.h
  utils/fill_nines.h
  utils/pow.c
Labels: API, bug, ready for review

#205 fix: Add the missing files to doxygen document
  accelerator/apis.c
  accelerator/message.h
  request/ta_send_mam.c
  request/ta_send_mam.h
  response/ta_send_mam.c
  response/ta_send_mam.h
  serializer/serializer.c
  serializer/serializer.h
  tests/driver.c
  tests/test_serializer.c
  utils/fill_nines.h
Labels: bug, ready for review

#206 fix(reg): Reslove regression port conflicts
  tests/regression/1_run_TA.sh
Labels: bug, ready for review

#212 refactor(api): Use entangled original APIs iota_client_get_tips and iota_client_get_transactions_to_approve
  accelerator/apis.c
  accelerator/common_core.c
  accelerator/common_core.h
  serializer/BUILD
  serializer/serializer.c
  serializer/serializer.h
  tests/test_common.cc
  tests/test_serializer.c
Labels: API, Ready for review

#215 refactor: Use utlist foreach instead for loop
  accelerator/common_core.c
Labels: Enhancement

#220 feat(hooks): Implement toolchains support
  .bazelrc
  WORKSPACE
  hooks/toolchains.rc
Labels: Deployment

#222 feat: Cleanup send/receive mam API
  WORKSPACE
  accelerator/apis.c
  tests/iota_api_mock.cc
  tests/iota_api_mock.hh
Labels: Enhancement

#223 feat(accel): Refactor send mam API
  accelerator/BUILD
  accelerator/apis.c
  accelerator/config.c
  accelerator/config.h
  map/BUILD
  map/mode.c
  map/mode.h
  request/ta_send_mam.c
  request/ta_send_mam.h
  serializer/serializer.c
  tests/BUILD
  tests/test_map_mode.c
  tests/test_serializer.c
Labels: Core, Ready for review

#225 feat(api): Enhance send mam API with length detection
  accelerator/apis.c
  map/mode.c
  map/mode.h
  request/BUILD
  request/ta_send_mam.c
  request/ta_send_mam.h
  serializer/serializer.c
  tests/test_map_mode.c
  tests/test_serializer.c
Labels: Enhancement, Ready for review

#224 fix: Fix regression and common core errors
  accelerator/apis.c
  accelerator/common_core.c
  tests/regression/1_close_TA.sh
  tests/regression/1_run_TA.sh
  tests/regression/1_run_TA_API.sh
  tests/regression/runner.py
Labels: Ready for review
