Repository DLTcollab/tangle-accelerator, pull requests merged in 2019-10, with the labels that each got.

#319 make keyspace can be specify by parameter --keyspace
  storage/scylla_api.c
  storage/scylla_api.h
  tests/test_scylla.c
Labels: A-storage, A-tests, C-bug, P-critical, S-work in progress

#324 cleanup(core): Remove deprecated function
  accelerator/common_core.h
Labels: A-core, C-cleanup

#326 improve(make): Separate MQTT from make all
  Makefile
Labels: A-mqtt, C-deployment, S-ready for review

#327 fix(readme): Synchronize build command
  README.md
Labels: C-doc

#328 cleanup: fix warnings in accelerator_mqtt
  README.md
  accelerator/config.c
  accelerator/config.h
  connectivity/mqtt/duplex_callback.c
  connectivity/mqtt/pub_utils.h
  connectivity/mqtt/sub_utils.c
Labels: C-cleanup

#308 feat(api): Implement IRI Proxy API
  accelerator/BUILD
  accelerator/apis.c
  accelerator/apis.h
  accelerator/http.h
  accelerator/proxy_apis.c
  accelerator/proxy_apis.h
  accelerator/server.cc
  tests/BUILD
  tests/driver.c
  tests/test_define.h
Labels: A-api, A-mqtt, C-feature, S-ready for review

#332 Refactor architecture of TA logger
  accelerator/BUILD
  accelerator/apis.c
  accelerator/common_core.c
  accelerator/config.c
  accelerator/config.h
  accelerator/conn_mqtt.c
  accelerator/errors.h
  accelerator/http.c
  accelerator/main.c
  accelerator/proxy_apis.c
  accelerator/proxy_apis.h
  accelerator/server.cc
  connectivity/mqtt/client_common.c
  connectivity/mqtt/duplex_callback.c
  connectivity/mqtt/duplex_callback.h
  connectivity/mqtt/duplex_utils.c
  connectivity/mqtt/pub_utils.c
  connectivity/mqtt/sub_utils.c
  serializer/BUILD
  serializer/serializer.c
  storage/scylla_api.h
  tests/driver.c
  tests/test_common.cc
  tests/test_pow.c
  tests/test_scylla.c
  tests/test_serializer.c
  utils/BUILD
  utils/backend_redis.c
  utils/logger.h
  utils/pow.c
Labels: S-ready for review

#329 Apply security rules
  connectivity/mqtt/BUILD
  connectivity/mqtt/duplex_callback.c
  hooks/pre-commit/03-function-check
  hooks/scripts/function_check
  serializer/BUILD
  serializer/serializer.c
  tests/driver.c
  tests/test_serializer.c
Labels: C-enhancement

#337 fix(server): Fix API TA info status code
  accelerator/server.cc
Labels: A-api, C-bug

#315 refactor(mam): Refactor MAM related APIs
  accelerator/BUILD
  accelerator/apis.c
  accelerator/common_core.c
  accelerator/common_core.h
  accelerator/errors.h
  map/BUILD
  map/mode.c
  map/mode.h
  request/ta_send_mam.c
  request/ta_send_mam.h
  response/BUILD
  response/ta_send_mam.c
  response/ta_send_mam.h
  serializer/serializer.c
  tests/BUILD
  tests/driver.c
  tests/test_define.h
  tests/test_serializer.c
  utils/bundle_array.h
Labels: A-api, A-mam, C-enhancement, C-feature, S-ready for review

#335 feat(api): Implement HTTP router of Proxy API
  README.md
  accelerator/BUILD
  accelerator/apis.c
  accelerator/apis.h
  accelerator/http.c
  accelerator/proxy_apis.c
  accelerator/proxy_apis.h
  accelerator/server.cc
  serializer/serializer.c
  serializer/serializer.h
  tests/driver.c
  tests/test_common.cc
  tests/test_define.h
  tests/test_serializer.c
  utils/BUILD
  utils/hash_algo_djb2.h
Labels: A-api, A-serializer, A-tests, C-feature
