Repository DLTcollab/tangle-accelerator, pull requests merged in 2019-08, with the labels that each got.

#259 fix(api): Fix send_tranfer() response format
  accelerator/apis.c
  serializer/serializer.c
  serializer/serializer.h
Labels: Bug, Ready for review

#250 feat(server): Implement MQTT protocol interface
  Doxyfile
  MQTT_server.md
  README.md
  accelerator/BUILD
  accelerator/config.h
  accelerator/errors.h
  accelerator/mqtt_interface.c
  connectivity/mqtt/BUILD
  connectivity/mqtt/client_common.c
  connectivity/mqtt/client_common.h
  connectivity/mqtt/duplex_callback.c
  connectivity/mqtt/duplex_callback.h
  connectivity/mqtt/duplex_utils.c
  connectivity/mqtt/duplex_utils.h
  connectivity/mqtt/pub_utils.c
  connectivity/mqtt/pub_utils.h
  connectivity/mqtt/sub_utils.c
  connectivity/mqtt/sub_utils.h
  third_party/BUILD
Labels: Enhancement, Ready for review

#269 feat(api): Add lock to avoid race condition
  accelerator/apis.c
  accelerator/apis.h
  accelerator/errors.h
  accelerator/main.c
  accelerator/server.cc
Labels: Core, Enhancement, Ready for review

#287 fix(MAM): Wrong datatype for MAM function
  accelerator/apis.c
  accelerator/common_core.c
  accelerator/common_core.h
Labels: Bug

#276 fear(API): Add MAM file to save configures
  accelerator/apis.c
  accelerator/apis.h
  accelerator/common_core.c
  accelerator/common_core.h
  accelerator/config.c
  accelerator/config.h
  accelerator/errors.h
  accelerator/http.c
  accelerator/main.c
  accelerator/server.cc
  map/mode.c
  request/ta_send_mam.h
  response/ta_send_mam.h
  serializer/serializer.c
  tests/driver.c
  tests/test_define.h
  tests/test_serializer.c
Labels: API

#265 feat(mqtt): Implement MQTT request handler
  README.md
  accelerator/BUILD
  accelerator/config.c
  accelerator/config.h
  accelerator/conn_mqtt.c
  connectivity/mqtt/BUILD
  connectivity/mqtt/client_common.h
  connectivity/mqtt/duplex_callback.c
  connectivity/mqtt/duplex_callback.h
  connectivity/mqtt/duplex_utils.c
  connectivity/mqtt/sub_utils.c
  connectivity/mqtt/usage.md
  serializer/serializer.c
  serializer/serializer.h
  tests/test_define.h
  tests/test_serializer.c
Labels: Enhancement
