Repository DLTcollab/tangle-accelerator, pull requests merged in 2020-01, with the labels that each got.

#386 Conditional build for ScyllaDB backend and its dependance
  README.md
  accelerator/BUILD
  accelerator/config.c
  accelerator/config.h
  accelerator/conn_mqtt.c
  accelerator/main.c
  accelerator/server.cc
  storage/BUILD
  tests/BUILD
  tests/driver.c
  tests/empty_test.c
  tests/test_common.cc
  tests/test_scylladb.c
Labels: A-storage, C-deployment

#388 Fix regression test
  accelerator/http.c
  tests/regression/0_build.sh
  tests/regression/1_run_TA_API.sh
  tests/regression/runner.py
Labels: A-tests, C-bug, P-high

#406 Fix memory leak on functions to processing HTTP requests
  accelerator/http.c
  accelerator/server.cc
Labels: A-router, C-bug

#409 fix: Fix miscellaneous request payload
  accelerator/http.c
  tests/test_common.cc
Labels: A-router, C-bug, P-critical

#363 Implement transaction reattachment related APIs
  README.md
  accelerator/BUILD
  accelerator/apis.c
  accelerator/apis.h
  accelerator/config.c
  accelerator/http.c
  accelerator/server.cc
  connectivity/mqtt/duplex_callback.c
  response/BUILD
  response/ta_send_transfer.h
  serializer/BUILD
  serializer/serializer.c
  serializer/serializer.h
  storage/scylladb_client.c
  storage/scylladb_client.h
  storage/scylladb_identity.c
  tests/driver.c
  tests/test_scylladb.c
Labels: A-api, A-storage, C-feature

#407 fix: Fix error as CLI argument without giving key
  accelerator/config.c
Labels: A-config, C-bug

#416 fix: Change the logger level from warning to info
  accelerator/main.c
Labels: A-router, C-enhancement

#411 fix(build): Fix wrong Makefile clean rule
  Makefile
Labels: C-bug

#422 fix(driver): Fix missing transaction hashes
  tests/test_define.h
Labels: A-tests, C-bug

#419 Use precise error message in http.c
  connectivity/http/http.c
Labels: A-router, C-bug

#420 refactor(regression): Revise test suite
  .gitignore
  tests/regression/common.py
  tests/regression/runner.py
  tests/regression/test_suite/generate_address.py
  tests/regression/test_suite/get_tips.py
  tests/regression/test_suite/get_tips_pair.py
  tests/regression/test_suite/get_transactions_object.py
  tests/regression/test_suite/send_transfer.py
  tests/regression/test_suite/send_trytes.py
Labels: A-tests, C-enhancement

#425 fix(http): Fix NULL request error under root path
  connectivity/http/http.c
Labels: A-router, C-bug, P-critical

#430 refactor(bazel): Sync entangled hooking commit
  WORKSPACE
Labels: C-deployment, C-enhancement

#433 refactor(bazel): Enhance bazel conditional build
  accelerator/BUILD
  accelerator/core/BUILD
  accelerator/core/response/BUILD
  accelerator/core/serializer/BUILD
  common/BUILD
  connectivity/mqtt/BUILD
  storage/BUILD
  tests/BUILD
Labels: A-config, C-enhancement, S-ready for review

#434 feat(formatter): Add buildifier in formatter
  hooks/formatter
Labels: C-enhancement

#427 fix(core): Fix resource leak
  accelerator/core/core.c
Labels: A-core, C-bug

#438 Fix incorrect assigned size and remove dead code
  accelerator/core/core.c
  accelerator/core/pow.c
Labels: C-bug, C-enhancement

#441 fix(req): Fix NULL pointer dereference
  accelerator/core/request/ta_find_transaction_objects.c
Labels: C-bug

#443 docs : Add Doxygen friendly file descriptions for TA storage
  storage/scylladb_client.h
  storage/scylladb_identity.h
  storage/scylladb_permanode.h
  storage/scylladb_utils.h
  storage/ta_storage.h
Labels: C-doc

#445 update(bazel): Synchronize entangled
  WORKSPACE
Labels: C-bug

#444 fix(doc): Add file description
  accelerator/core/pow.h
  connectivity/http/http.h
  connectivity/mqtt/duplex_callback.h
  connectivity/mqtt/duplex_utils.h
  connectivity/mqtt/mqtt_common.h
  connectivity/mqtt/pub_utils.h
  connectivity/mqtt/sub_utils.h
  utils/cache/cache.h
  utils/fill_nines.h
  utils/hash_algo_djb2.h
  utils/timer.h
Labels: C-doc

#429 feat(db): Implement transaction reattach service
  docs/reattacher.md
  reattacher/BUILD
  reattacher/reattacher_main.c
  storage/scylladb_identity.c
  storage/scylladb_identity.h
  tests/test_scylladb.c
Labels: A-storage, C-feature

#446 fix(cli): Append zeros in CLI option array
  accelerator/cli_info.h
  accelerator/config.c
Labels: A-config, C-bug

#448 cleanup(http): Fix warnings in bazel rule accelerator
  connectivity/http/http.c
  tests/test_core.cc
Labels: C-cleanup

#451 fix : continue to get cli options after an unknown option
  accelerator/config.c
  reattacher/reattacher_main.c
  tests/test_scylladb.c
Labels: A-config, C-bug

#450 doc(CONTRIBUTING): Add Contributing notice
  CONTRIBUTING.md
Labels: C-doc

#435 feat(regression): Allow different build options
  connectivity/http/BUILD
  connectivity/http/http.c
  tests/regression/0_build.sh
  tests/regression/1_run_TA_API.sh
  tests/regression/common.py
  tests/regression/common.sh
  tests/regression/requirements.txt
  tests/regression/run-api-with-mqtt.sh
  tests/regression/run-api.sh
  tests/regression/runner.py
  tests/regression/test_suite/generate_address.py
  tests/regression/test_suite/get_tips.py
  tests/regression/test_suite/get_tips_pair.py
  tests/regression/test_suite/get_transactions_object.py
  tests/regression/test_suite/send_transfer.py
  tests/regression/test_suite/send_trytes.py
Labels: A-tests, C-enhancement

#457 docs(README): Add requirements for makefile
  README.md
Labels: C-doc

#462 fix(logger): Fix wrong logger name
  accelerator/main.c
  accelerator/mqtt_main.c
  connectivity/http/http.c
Labels: C-bug

#453 feat(config): Add CLI for MQTT configures
  accelerator/cli_info.h
  accelerator/config.c
  accelerator/mqtt_main.c
  docs/build.md
Labels: A-config, A-mqtt, C-feature
