Repository DLTcollab/tangle-accelerator, pull requests merged in 2020-04, with the labels that each got.

#541 chore: add uuid-runtime package to docker image
  WORKSPACE
  accelerator/BUILD
Labels: C-deployment

#550 fix(hooks): Format WORKSPACE with formatter
  WORKSPACE
  hooks/formatter
Labels: C-bug, C-refactor

#524 feat(cache): Implement LIST operations for cache
  tests/test_define.h
  tests/unit-test/test_cache.c
  utils/cache/backend_redis.c
  utils/cache/cache.h
Labels: A-storage, C-feature

#548 Remove obsolete permanode implementation
  storage/BUILD
  storage/scylladb_permanode.c
  storage/scylladb_permanode.h
  storage/ta_storage.h
  tests/unit-test/test_scylladb.c
Labels: A-storage, C-cleanup, S-blocked

#553 refactor: Reorder structure members to save extra memory
  accelerator/config.h
  connectivity/mqtt/mqtt_common.h
Labels: C-performance, C-refactor

#537 feat(config): Add CLI command to disable GTTA
  accelerator/cli_info.h
  accelerator/config.c
  accelerator/config.h
  accelerator/core/apis.c
  accelerator/core/apis.h
  accelerator/core/core.c
  accelerator/core/core.h
  connectivity/http/http.c
  tests/api/driver.c
Labels: A-config, C-refactor

#555 Fix Travis CI and Coverity Scan
  .travis.yml
Labels: A-tests, C-deployment

#538 fix(main): Fix unmatching argument type of pthread
  accelerator/main.c
Labels: C-cleanup

#530 feat(MQTT): Add missing routes
  accelerator/cli_info.h
  accelerator/core/serializer/serializer.h
  common/macros.h
  common/ta_errors.c
  common/ta_errors.h
  connectivity/common.c
  connectivity/mqtt/BUILD
  connectivity/mqtt/duplex_callback.c
  connectivity/mqtt/duplex_utils.c
  connectivity/mqtt/mqtt_common.h
  connectivity/mqtt/usage.md
Labels: A-mqtt, C-refactor

#512 feat(mam): Implement send message serializer
  accelerator/core/apis.c
  accelerator/core/apis.h
  accelerator/core/core.h
  accelerator/core/mam_core.c
  accelerator/core/mam_core.h
  accelerator/core/request/ta_recv_mam.c
  accelerator/core/request/ta_recv_mam.h
  accelerator/core/request/ta_send_mam.c
  accelerator/core/request/ta_send_mam.h
  accelerator/core/serializer/serializer.c
  common/macros.h
  connectivity/http/http.c
  tests/api/driver.c
  tests/api/mam_test.c
  tests/test_define.h
  tests/unit-test/test_serializer.c
Labels: A-mam, C-feature, S-ready for review

#526 feat(core): Broadcast buffered transaction objects
  accelerator/config.c
  accelerator/config.h
  accelerator/core/BUILD
  accelerator/core/apis.c
  accelerator/core/apis.h
  accelerator/core/core.c
  accelerator/core/core.h
  accelerator/core/response/ta_send_transfer.c
  accelerator/core/response/ta_send_transfer.h
  accelerator/core/serializer/serializer.c
  accelerator/main.c
  common/macros.h
  tests/api/BUILD
  tests/api/common.c
  tests/api/common.h
  tests/api/driver.c
  tests/api/driver_core.c
  tests/api/mam_test.c
  utils/cache/backend_redis.c
  utils/cache/cache.h
Labels: A-core, C-feature, S-ready for review

#564 fix(test): Allow driver_core_cli_init take NULL args
  tests/api/common.c
Labels: A-tests, C-bug, C-deployment

#568 feat(config): Set buffer list name with CLI
  accelerator/cli_info.h
  accelerator/config.c
Labels: A-config, A-tests, C-bug, C-feature

#563 fix(http): Report when requested msg too long
  accelerator/core/serializer/serializer.c
  common/ta_errors.c
  common/ta_errors.h
  connectivity/common.c
  connectivity/common.h
Labels: A-router, C-bug

#581 fix(common): correct undeclared macro for HTTP message
  connectivity/common.c
Labels: A-router, C-bug

#557 feat(api): Implement api_fetch_txn_with_uuid()
  accelerator/core/apis.c
  accelerator/core/apis.h
  accelerator/core/core.c
  accelerator/core/core.h
  accelerator/core/response/response.h
  accelerator/core/response/ta_fetch_txn_with_uuid.c
  accelerator/core/response/ta_fetch_txn_with_uuid.h
  accelerator/core/serializer/serializer.c
  accelerator/core/serializer/serializer.h
  tests/api/driver.c
  tests/api/driver_core.c
  tests/test_define.h
  tests/unit-test/test_cache.c
  tests/unit-test/test_serializer.c
  utils/cache/backend_redis.c
  utils/cache/cache.h
Labels: A-api, A-core, C-feature

#566 feat(common): Implement debugging tool
  accelerator/core/BUILD
  accelerator/core/core.h
  common/BUILD
  common/debug.c
  common/debug.h
Labels: A-tests, C-feature
